export interface Property {
  id: string
  title: string
  description?: string
  handle?: string
  price: number
  transaction_type: 'vente' | 'location' | 'rent' | 'sale'
  property_type: 'appartement' | 'maison' | 'terrain' | 'local_commercial' | 'parking' | 'autre'
  status: 'disponible' | 'sous_offre' | 'vendu' | 'loue'
  address?: string
  city?: string
  postal_code?: string
  latitude?: number
  longitude?: number
  surface?: number
  acreage?: number
  rooms?: number
  bedrooms?: number
  bathrooms?: number
  floor?: number
  max_guests?: number
  balcony?: boolean
  terrace?: boolean
  garden?: boolean
  elevator?: boolean
  furnished?: boolean
  parking?: number
  energy_class?: string
  heating_type?: string
  construction_year?: number
  charges?: number
  tax_fonciere?: number
  sale_off?: number
  featured_image?: string
  slug?: string
  published?: boolean
  is_ads?: boolean
  views_count?: number
  like_count?: number
  review_rating?: number
  review_count?: number
  created_at?: string
  updated_at?: string
  listing_date?: string
  note_moyenne?: number
  nombre_avis?: number
  nombre_invites_max?: number
  surface_pieds_carres?: number
  agence_id?: string
  agent_id?: string
  prix_hors_honoraires?: number
  honoraires?: number
  honoraires_charge?: string
  reference_mandat?: string
  reference_interne?: string
  disponibilite?: string
  surface_habitable?: number
  surface_totale?: number
  nombre_wc?: number
  nombre_sde?: number
  adresse_complete?: string
  etage?: number
  nombre_etages_total?: number
  ascenseur?: boolean
  chauffage_type?: string
  chauffage_energie?: string
  chauffage_systeme?: string
  eau_chaude_type?: string
  eau_chaude_energie?: string
  dpe_valeur?: number
  ges_valeur?: number
  charges_copropriete?: number
  nombre_lots?: number
  cave?: boolean
  cellier?: boolean
  grenier?: boolean
  garage?: boolean
  climatisation?: boolean
  cuisine_equipee?: boolean
  cuisine_americaine?: boolean
  interphone?: boolean
  gardien?: boolean
  piscine?: boolean
  surface_sejour?: number
  veranda?: boolean
  energie_depenses_min?: number
  energie_depenses_max?: number
  dpe_date?: string
  deleted_at?: string | null
  ubiflow_active?: boolean
  hide_address?: boolean
  property_label?: string
  is_featured?: boolean
}